import BoxHighlight from '@renderer/assets/animations/box-highlight.svg?react'
import FlipClock from '@renderer/assets/animations/flip-clock.svg?react'
import Highlight from '@renderer/assets/animations/highlight.svg?react'
import Karaoke from '@renderer/assets/animations/karaoke.svg?react'
import Impact from '@renderer/assets/animations/impact.svg?react'
import Reveal from '@renderer/assets/animations/reveal.svg?react'

export const PROJECTS_LIMIT = 10

export const FONTS_FAMILIES = [
  'Abril Fatface',
  'Aclonica',
  'Advent Pro',
  'Albert Sans',
  'Alegreya',
  'Alegreya SC',
  'Alegreya Sans',
  'Alegreya Sans SC',
  'Aleo',
  'Alex Brush',
  'Alfa Slab One',
  'Allison',
  'Almendra',
  'Alumni Sans',
  'Alumni Sans Inline One',
  'Amaranth',
  'Amatic SC',
  'Amiri',
  'Andada Pro',
  'Andika',
  'Anonymous Pro',
  'Anton',
  'Anybody',
  'Archivo',
  'Archivo Black',
  'Archivo Narrow',
  'Arimo',
  'Arsenal',
  'Arvo',
  'Asap',
  'Asap Condensed',
  'Astloch',
  'Atkinson Hyperlegible',
  'Averia Libre',
  'Averia Sans Libre',
  'Averia Serif Libre',
  'Azeret Mono',
  'B612',
  'B612 Mono',
  'Bad Script',
  'Bai Jamjuree',
  'Ballet',
  'Balsamiq Sans',
  'Bangers',
  'Barlow',
  'Barlow Condensed',
  'Barlow Semi Condensed',
  'Bayon',
  'Be Vietnam Pro',
  'Bebas Neue',
  'Bellota',
  'Bellota Text',
  'Berkshire Swash',
  'Besley',
  'BhuTuka Expanded One',
  'Bitter',
  'Bodoni Moda',
  'Bona Nova',
  'Brygada 1918',
  'Bungee',
  'Bungee Hairline',
  'Bungee Inline',
  'Bungee Shade',
  'Cabin',
  'Cabin Condensed',
  'Cabin Sketch',
  'Caladea',
  'Calistoga',
  'Cambay',
  'Cantarell',
  'Cardo',
  'Carlito',
  'Castoro',
  'Caudex',
  'Caveat',
  'Chakra Petch',
  'Charis SIL',
  'Chewy',
  'Chivo',
  'Chivo Mono',
  'Chonburi',
  'Cinzel',
  'Cinzel Decorative',
  'Coda',
  'Comic Neue',
  'Concert One',
  'Contrail One',
  'Cormorant',
  'Cormorant Garamond',
  'Cormorant Infant',
  'Courier Prime',
  'Cousine',
  'Crimson Pro',
  'Crimson Text',
  'Cuprum',
  'DM Sans',
  'Damion',
  'Dancing Script',
  'Dela Gothic One',
  'Dosis',
  'EB Garamond',
  'East Sea Dokdo',
  'Economica',
  'Epilogue',
  'Exo',
  'Exo 2',
  'Expletus Sans',
  'Fahkwang',
  'Familjen Grotesk',
  'Faustina',
  'Figtree',
  'Finger Paint',
  'Finlandica',
  'Fira Code',
  'Fira Sans',
  'Fira Sans Condensed',
  'Fira Sans Extra Condensed',
  'Fjalla One',
  'Fraunces',
  'GFS Neohellenic',
  'Gantari',
  'Gelasio',
  'Genos',
  'Gentium Book Plus',
  'Gentium Plus',
  'Georama',
  'Glory',
  'Gochi Hand',
  'Grandstander',
  'Grenze',
  'Gruppo',
  'Gudea',
  'Hanken Grotesk',
  'Homemade Apple',
  'IBM Plex Mono',
  'IBM Plex Sans',
  'IBM Plex Sans Condensed',
  'IBM Plex Serif',
  'IM Fell DW Pica',
  'IM Fell DW Pica SC',
  'Ibarra Real Nova',
  'Iceberg',
  'Inria Sans',
  'Inria Serif',
  'Instrument Sans',
  'Inter',
  'Inter Tight',
  'Istok Web',
  'JetBrains Mono',
  'Josefin Sans',
  'Josefin Slab',
  'Jost',
  'Judson',
  'Julius Sans One',
  'Just Another Hand',
  'K2D',
  'Kanit',
  'Kantumruy Pro',
  'Karla',
  'KoHo',
  'Kodchasan',
  'Krub',
  'Kufam',
  'Kulim Park',
  'Kumar One Outline',
  'Labrada',
  'Lalezar',
  'Lato',
  'League Gothic',
  'League Script',
  'League Spartan',
  'Lekton',
  'Lemon',
  'Libre Baskerville',
  'Libre Bodoni',
  'Libre Caslon Text',
  'Libre Franklin',
  'Licorice',
  'Literata',
  'Livvic',
  'Lobster',
  'Lobster Two',
  'Lora',
  'Luckiest Guy',
  'Mali',
  'Manuale',
  'Marvel',
  'Meow Script',
  'Merriweather',
  'Merriweather Sans',
  'Metamorphous',
  'Modak',
  'Mohave',
  'Monoton',
  'Montagu Slab',
  'Montserrat',
  'Montserrat Alternates',
  'Mr De Haviland',
  'Mulish',
  'MuseoModerno',
  'Neuton',
  'New Rocker',
  'Newsreader',
  'Niramit',
  'Nobile',
  'Notable',
  'Noticia Text',
  'Noto Sans',
  'Noto Sans Display',
  'Noto Sans JP',
  'Noto Sans KR',
  'Noto Serif',
  'Noto Serif Display',
  'Noto Serif JP',
  'Noto Serif KR',
  'Noto Serif Tamil',
  'Nunito',
  'Nunito Sans',
  'Oi',
  'Old Standard TT',
  'Oleo Script',
  'Oooh Baby',
  'Open Sans',
  'Orelega One',
  'Oswald',
  'Overlock',
  'Overpass',
  'PT Sans',
  'PT Serif',
  'Pacifico',
  'Pangolin',
  'Passion One',
  'Pathway Extreme',
  'Patrick Hand',
  'Permanent Marker',
  'Petit Formal Script',
  'Petrona',
  'Philosopher',
  'Piazzolla',
  'Playball',
  'Playfair',
  'Playfair Display',
  'Playfair Display SC',
  'Plus Jakarta Sans',
  'Poltawski Nowy',
  'Poppins',
  'Press Start 2P',
  'Prompt',
  'Proza Libre',
  'Public Sans',
  'Puritan',
  'Quantico',
  'Quattrocento Sans',
  'Quicksand',
  'Racing Sans One',
  'Radio Canada',
  'Rakkas',
  'Raleway',
  'Rambla',
  'Rasa',
  'Red Hat Display',
  'Red Hat Mono',
  'Red Hat Text',
  'Righteous',
  'Roboto',
  'Roboto Condensed',
  'Roboto Mono',
  'Roboto Serif',
  'Rochester',
  'Rokkitt',
  'Rosario',
  'Rubik',
  'Rubik Bubbles',
  'Rubik Mono One',
  'Rubik Puddles',
  'Rubik Spray Paint',
  'Rubik Vinyl',
  'Rufina',
  'Russo One',
  'Rye',
  'STIX Two Text',
  'Sacramento',
  'Saira',
  'Sansita',
  'Sarabun',
  'Scada',
  'Schibsted Grotesk',
  'Secular One',
  'Sedgwick Ave',
  'Seymour One',
  'Shantell Sans',
  'Share',
  'Short Stack',
  'Shrikhand',
  'Silkscreen',
  'Six Caps',
  'Sofia Sans',
  'Sofia Sans Condensed',
  'Sofia Sans Extra Condensed',
  'Sofia Sans Semi Condensed',
  'Solway',
  'Song Myung',
  'Sono',
  'Source Code Pro',
  'Source Sans 3',
  'Source Serif 4',
  'Space Mono',
  'Spectral',
  'Spectral SC',
  'Spline Sans',
  'Spline Sans Mono',
  'Squada One',
  'Staatliches',
  'Syncopate',
  'Syne',
  'Taviraj',
  'Texturina',
  'Thasadith',
  'Tillana',
  'Tinos',
  'Titan One',
  'Titillium Web',
  'Tomorrow',
  'Tourney',
  'Trirong',
  'Trochut',
  'Ubuntu',
  'Ubuntu Mono',
  'Ultra',
  'Uncial Antiqua',
  'UnifrakturMaguntia',
  'Unna',
  'Urbanist',
  'Volkhov',
  'Vollkorn',
  'Wix Madefor Text',
  'Work Sans',
  'Yantramanav',
  'Yellowtail',
  'Yeseva One',
  'Yrsa',
  'Ysabeau',
  'ZCOOL KuaiLe',
  'Zen Maru Gothic',
  'Zilla Slab',
  'Zilla Slab Highlight'
]

export enum AnimationType {
  BoxHighlight = 'Box Highlight',
  FlipClock = 'Flip Clock',
  Highlight = 'Highlight',
  Karaoke = 'Karaoke',
  Impact = 'Impact',
  Reveal = 'Reveal'
}

export type AnimationConfig = {
  colorRequired: boolean
  icon: Icon
}

export const ANIMATIONS: Record<AnimationType, AnimationConfig> = {
  [AnimationType.BoxHighlight]: { colorRequired: true, icon: BoxHighlight },
  [AnimationType.FlipClock]: { colorRequired: false, icon: FlipClock },
  [AnimationType.Highlight]: { colorRequired: false, icon: Highlight },
  [AnimationType.Karaoke]: { colorRequired: false, icon: Karaoke },
  [AnimationType.Impact]: { colorRequired: false, icon: Impact },
  [AnimationType.Reveal]: { colorRequired: false, icon: Reveal }
}

export const DEFAULT_ANIMATION_COLOR = '#000000FF'

export const DEFAULT_ANIMATION = AnimationType.BoxHighlight

export const DEFAULT_TEXT_COLOR = '#FFFFFFFF'
