import { Subtitle } from '@renderer/store/store'
import { SubtitleFormat } from './SubtitleList.types'
import Konva from 'konva'

export function generateSRT(subtitles: Subtitle[]): string {
  return subtitles
    .map((subtitle, index) => {
      const start = formatTime(subtitle.start, SubtitleFormat.SRT)
      const end = formatTime(subtitle.end, SubtitleFormat.SRT)
      return `${index + 1}\n${start} --> ${end}\n${subtitle.text}\n`
    })
    .join('\n')
}

export function generateVTT(subtitles: Subtitle[]): string {
  return (
    'WEBVTT\n\n' +
    subtitles
      .map((subtitle) => {
        const start = formatTime(subtitle.start, SubtitleFormat.VTT)
        const end = formatTime(subtitle.end, SubtitleFormat.VTT)
        return `${start} --> ${end}\n${subtitle.text}\n`
      })
      .join('\n')
  )
}

function generateTXT(subtitles: Subtitle[]): string {
  return subtitles.map((subtitle) => `${subtitle.text}\n`).join('')
}

export function downloadSubtitles(subtitles: Subtitle[], format: SubtitleFormat): void {
  const content =
    format === SubtitleFormat.SRT
      ? generateSRT(subtitles)
      : format === SubtitleFormat.VTT
        ? generateVTT(subtitles)
        : generateTXT(subtitles)

  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)

  const a = document.createElement('a')
  a.href = url
  a.download = `subtitles.${format}`
  document.body.appendChild(a)
  a.click()

  // Cleanup
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function formatTime(seconds: number, format?: SubtitleFormat): string {
  const formattedTime = new Date(seconds * 1000).toISOString()
  if (format === SubtitleFormat.SRT) return formattedTime.slice(11, -1).replace('.', ',')
  if (format === SubtitleFormat.VTT) return formattedTime.slice(11, -1)
  if (format === SubtitleFormat.ASS) {
    // Calculate hours, minutes, seconds, and centiseconds for ASS format
    let totalSeconds = seconds
    const hours = Math.floor(totalSeconds / 3600)
    totalSeconds %= 3600
    const minutes = Math.floor(totalSeconds / 60)
    const secs = Math.floor(totalSeconds % 60)
    const centiseconds = Math.floor((totalSeconds - secs) * 100)

    // Pad hours, minutes, seconds, and centiseconds with leading zeros if necessary
    const hoursPadded = String(hours).padStart(1, '0')
    const minutesPadded = String(minutes).padStart(2, '0')
    const secondsPadded = String(secs).padStart(2, '0')
    const centisecondsPadded = String(centiseconds).padStart(2, '0')

    return `${hoursPadded}:${minutesPadded}:${secondsPadded}.${centisecondsPadded}`
  }
  // UI display format e.g. 01:12.5
  const uiDisplayFormat = formattedTime.slice(11, -3)
  const hoursEndIndex = uiDisplayFormat.indexOf(':')
  const hours = parseInt(uiDisplayFormat.slice(0, hoursEndIndex))
  return hours > 0 ? uiDisplayFormat : uiDisplayFormat.slice(hoursEndIndex + 1)
}

export function isSubtitlePlaying(currentTime: number, start: number, end: number): boolean {
  return +currentTime.toFixed(2) >= +start.toFixed(2) && +currentTime.toFixed(2) < +end.toFixed(2)
}

export function generateASS(
  canvasWidth: number,
  canvasHeight: number,
  styleProps: Konva.TextConfig,
  subtitles: Subtitle[]
): string {
  const { fontSize, rotation, x, y } = styleProps
  return `[Script Info]
; Script generated by Subtify
Title: Sample Subtitle
Original Script: User
ScriptType: v4.00+
Collisions: Normal
PlayDepth: 0
LayoutResX: ${canvasWidth}
LayoutResY: ${canvasHeight}
PlayResX: ${canvasWidth}
PlayResY: ${canvasHeight}

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default, Arial, ${fontSize}, &H00FFFFFF, &H000000FF, &H00000000, &HFF000000, 0, 0, 0, 0, 100, 100, 1, ${-rotation!}, 3, 1, 0, 2, 0, 0, 0, 1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
${subtitles
  .map((subtitle) => {
    const start = formatTime(subtitle.start, SubtitleFormat.ASS)
    const end = formatTime(subtitle.end, SubtitleFormat.ASS)
    return `Dialogue: 0,${start},${end},Default,,0,0,0,,{\\an7\\pos(${x},${y})}${subtitle.text}`
  })
  .join('\n')}
`
}
